version: '3.8'
services:
  redis-server-1:
    image: redis:7.4.1-alpine
    container_name: redis-server-1
    restart: always
    ports:
      - '63791:6379'
    command: redis-server --save "" --loglevel warning